reloader:
  watchGlobally: true
  namespaceSelector: "kubernetes.io/metadata.name in (python-ai-non-gpu,python-ai-gpu,python-ai-api-non-gpu,stg,web-api)"
  ignoreJobs: true
  logLevel: info
  reloadStrategy: annotations
  deployment:
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 512Mi
