name: python-ai-non-gpu
clusterPrefixName: ai-non-gpu-eks
deployment:
  enabled: true
  image:
    name: python-ai
    tag: 'demo_ecaaa4d'
  replicas: 1
  deploymentStrategy: RollingUpdate
  maxSurge: 25%
  maxUnavailable: 25%
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    admission.datadoghq.com/enabled: "false"
    tags.datadoghq.com/service: python-ai-non-gpu
    tags.datadoghq.com/project: python-ai
    tags.datadoghq.com/team: algo
    tags.datadoghq.com/env: demo
  podAnnotations:
    ad.datadoghq.com/python-ai-non-gpu.logs: '[{"source":"python-ai", "service":"python-ai-non-gpu", "tags":["env:demo","project:python-ai","team:algo"]}]'
# command: sleep 3000
# autoscaling:
#   minReplicas: 1
#   maxReplicas: 2

serviceAccount:
  create: false

service:
  enabled: true
  targetPort: 80

additionalEnvsFrom:
  - name: HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

additionalEnvs:
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://$(HOST_IP):4318"

config:
  data:
    AI_LOG_LEVEL: "DEBUG"
    S3_BUCKET: "demo-euc1-example-projects"
    S3_REGION: "eu-central-1"
secrets:
  storeKind: ClusterSecretStore
  storeName: applications-cluster-store
  template:
    AWS_ACCESS_KEY_ID: "{{ .s3_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ .s3_secret }}"
    LLM_API_KEY: "{{ .open_ai_key }}"
  data:
    - secretKey: open_ai_key
      remoteRef:
        key: "Application/example/default-secret"
        property: "OPEN_AI_KEY"  
    - secretKey: s3_access_key
      remoteRef:
        key: "Application/example/default-secret"
        property: "S3_ACCESS_KEY"
    - secretKey: s3_secret
      remoteRef:
        key: "Application/example/default-secret"
        property: "S3_SECRET"
ingress:
  enabled: true
  groupName: demo-euc1-ai-non-gpu-eks-private
  internet: false
  annotations:
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=360
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-Res-2021-06
    alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:eu-central-1:123456789012:regional/webacl/demo-euc1-waf-acl-regional/00000000-0000-0000-0000-000000000000"
    
resources:
  limits:
    memory: "20Gi"
    cpu: "5"
  requests:
    memory: "18Gi"
    cpu: "4"
nodeSelector:
  workload-type: worker
  karpenter.k8s.aws/instance-family: "m5zn"

tolerations:
  - key: workload-type
    value: worker
    operator: Equal
    effect: NoSchedule
