apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ai-api-non-gpu-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  ai-api-non-gpu: "true"
          - git:
              repoURL: https://github.com/gatmbarz123/AWS-Project.git
              revision: main
              directories:
                - path: regions/eu-central-1/environments/production/clusters/{{.name}}/values/apps/*
              
  template:      
    metadata:
      name: "{{.name}}-{{.path.basename}}"
      namespace: argocd

    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      sources:
      - repoURL: https://github.com/gatmbarz123/AWS-Project.git
        targetRevision: main
        ref: values

      - repoURL: https://github.com/gatmbarz123/AWS-Project.git
        targetRevision: main
        path: 'chart'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - $values/regions/eu-central-1/environments/production/clusters/global-values.yaml
            - $values/regions/eu-central-1/environments/production/clusters/{{.name}}/values/apps/{{.path.basename}}/values.yaml
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: "{{.server}}"
        namespace: "prod"

      # Sync policy
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
