apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-secret-stores
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: enabled
                    operator: NotIn
                    values:
                      - "false"
          - git:
              repoURL: https://github.com/gatmbarz123/AWS-Project.git
              revision: main
              directories:
                - path: regions/eu-central-1/environments/production/clusters/{{.name}}/values/cluster-addons/applications-secret-store
                - path: regions/eu-central-1/environments/production/clusters/{{.name}}/values/cluster-addons/datadog-secret-store
           
  template:      
    metadata:
      name: "{{.name}}-{{.path.basename}}"
      namespace: argocd

    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      source:
        repoURL: https://github.com/gatmbarz123/AWS-Project.git
        targetRevision: main
        path: "{{.path.path}}"
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - /regions/eu-central-1/environments/production/clusters/global-values.yaml
            - /regions/eu-central-1/environments/production/clusters/{{.name}}/values/cluster-addons/{{.path.basename}}/values.yaml
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: "{{.server}}"
        namespace: '{{ if contains "web" .name }}argocd{{ else }}external-secrets{{ end }}'

      # Sync policy
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true
