apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: default-node-pools
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchExpressions:
          - key: enabled
            operator: NotIn
            values:
              - "false"
  template:      
    metadata:
      name: '{{name}}-default-node-pool'
      namespace: argocd

    spec:
      # The project the application belongs to.
      project: default
      # Source of the application manifests
      source:
        repoURL: 'https://github.com/gatmbarz123/AWS-Project.git'
        targetRevision: main
        path: ./regions/eu-central-1/environments/staging/cluster-addons/default-node-pools
        helm:
          valueFiles:
          - /regions/eu-central-1/environments/staging/cluster-addons/default-node-pools/values.yaml
          - /regions/eu-central-1/environments/staging/clusters/{{name}}/values/cluster-addons/node-pools/values.yaml
      destination:
        server: "{{server}}"
        namespace: karpenter
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true
