serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/dev-euc1-web-eks-private-eks-external-dns

env:
  - name: AWS_DEFAULT_REGION
    value: eu-central-1
txtOwnerId: dev-euc1-web-eks-private

