karpenter:
  iamRole: "karpenter-eks-node-group-20260306190730379600000017"

clusterName: "dev-usgw1-python-ai-eks"
clusterVersion: "1.33"
   
 
nodePools:
  - name: worker-nodepool
    taints:
      - key: workload-type
        value: worker
        effect: NoSchedule
    labels:
      workload-type: worker
    requirements:
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
          - m6i
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
          - xlarge
          - 2xlarge
          - 4xlarge
          - 8xlarge
          - 12xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values: 
          - on-demand

  - name: api-nodepool
    taints:
      - key: workload-type
        value: api
        effect: NoSchedule
    labels:
      workload-type: api
    requirements:
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: 
          - t
          - c
          - r
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values: 
          - medium
          - large
          - xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values: 
          - on-demand

  - name: gpu-nodepool
    taints:
      - key: nvidia.com/gpu
        value: "true"
        effect: NoSchedule
      - key: workload-type
        value: gpu
        effect: NoSchedule
    labels:
      workload-type: gpu
      nvidia.com/gpu: "true"
    requirements:
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
          - g4dn
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values: 
          - xlarge
          - 2xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values: 
          - spot
      - key: "topology.kubernetes.io/zone"
        operator: In
        values:
          - us-gov-west-1a
          - us-gov-west-1b
          - us-gov-west-1c
      - key: "kubernetes.io/arch"
        operator: In
        values:
          - amd64
      - key: "kubernetes.io/os"
        operator: In
        values:
          - linux