apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-external-secret
  namespace: {{ .Values.namespace }} 
  {{- if .Values.secrets.annotations }}
  annotations:
    {{- range $key, $value := .Values.secrets.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  refreshInterval: 10h
  secretStoreRef:
    name: datadog-secretstore
    kind: SecretStore
  target:
    name: datadog-api-secret
    creationPolicy: Owner
    {{- if .Values.secrets.template }}
    template:
      engineVersion: v2
      data:
        {{- toYaml .Values.secrets.template | nindent 8 }}
    {{- end }}
  data:
{{- range $item := .Values.secrets.data }}
  - secretKey: "{{ $item.secretKey }}"
    remoteRef:
      key: "{{ $item.remoteRef.key }}"
      property: "{{ $item.remoteRef.property }}"
{{- end }}
