serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws-us-gov:iam::123456789012:role/dev-usgw1-python-ai-eks-private-eks-external-dns

env:
  - name: AWS_DEFAULT_REGION
    value: us-gov-west-1
txtOwnerId: dev-usgw1-python-ai-eks-private

