name: python-ai-edge-non-gpu

clusterPrefixName: python-ai-eks

deployment:
  enabled: true
  image:
    name: python-ai
    tag: 'dev_a6efa66'
  replicas: 1
  deploymentStrategy: RollingUpdate
  maxSurge: 25%
  maxUnavailable: 25%
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    admission.datadoghq.com/enabled: "false"
    tags.datadoghq.com/service: python-ai-edge-non-gpu
    tags.datadoghq.com/project: python-ai
    tags.datadoghq.com/team: algo
    tags.datadoghq.com/env: dev
  podAnnotations:
    ad.datadoghq.com/python-ai-edge-non-gpu.logs: '[{"source":"python-ai", "service":"python-ai-edge-non-gpu", "tags":["env:dev","project:python-ai","team:algo"]}]'

# autoscaling:
#   minReplicas: 1
#   maxReplicas: 2

serviceAccount:
  create: false

service:
  enabled: true
  targetPort: 80

config:
  data:
    AI_LOG_LEVEL: "DEBUG"
    S3_BUCKET: "dev-euc1-example-projects"
    S3_REGION: "eu-central-1"
    APP_VERSION: "1.0.0"

secrets:
  storeKind: ClusterSecretStore
  storeName: applications-cluster-store
  template:
    AWS_ACCESS_KEY_ID: "{{ .s3_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ .s3_secret }}"
  data:
    - secretKey: s3_access_key
      remoteRef:
        key: "Application/example/default-secret"
        property: "S3_ACCESS_KEY"
    - secretKey: s3_secret
      remoteRef:
        key: "Application/example/default-secret"
        property: "S3_SECRET"

ingress:
  enabled: true
  groupName: dev-euc1-ai-edge-non-gpu-eks-private
  internet: false
  annotations:
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=360
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-Res-2021-06
    alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:eu-central-1:123456789012:regional/webacl/dev-euc1-waf-acl-regional/00000000-0000-0000-0000-000000000000"

resources:
  limits:
    memory: "45Gi"
    cpu: "11"
  requests:
    memory: "16Gi"
    cpu: "4"

nodeSelector:
  workload-type: edge
  karpenter.k8s.aws/instance-family: "m5zn"
  karpenter.k8s.aws/instance-size: "3xlarge"

tolerations:
  - key: workload-type
    value: edge
    operator: Equal
    effect: NoSchedule
