apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  role: {{ .Values.karpenter.iamRole }}
  subnetSelectorTerms:
    - tags:
        'karpenter.sh/discovery/{{ .Values.clusterName }}': "true"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}
  amiSelectorTerms:
    - name: 'amazon-eks-node-al2023-x86_64-standard-{{ .Values.clusterVersion }}-*'
  tags:
    karpenter.sh/discovery: {{ .Values.clusterName }}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        iops: 3000
        encrypted: true
        deleteOnTermination: true
  userData: |
    #!/bin/bash
    echo "FIPS post-nodeadm $(date)"
    dnf update -y
    dnf -y install crypto-policies crypto-policies-scripts
    fips-mode-setup --enable
    reboot