global:
  certificate: "arn:aws-us-gov:acm:us-gov-west-1:123456789012:certificate/00000000-0000-0000-0000-000000000000"
  example_public_hostname: dev.usgw1.example.com
  example_private_hostname: dev.usgw1.example.com
