karpenter:
  iamRole: "karpenter-eks-node-group-2026012608375178270000000c"

clusterName: "dev-euc1-python-ai-eks"
clusterVersion: "1.35"
   
 
nodePools:
  - name: worker-nodepool
    taints:
      - key: workload-type
        value: worker
        effect: NoSchedule
    labels:
      workload-type: worker
    requirements:
      - key: workload-type
        operator: In
        values:
          - worker
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: 
          - m
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values: 
          - m5zn
          - m6i
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values: 
          - xlarge
          - 2xlarge
          - 3xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values: 
          - on-demand

  - name: api-nodepool
    taints:
      - key: workload-type
        value: api
        effect: NoSchedule
    labels:
      workload-type: api
    requirements:
      - key: workload-type
        operator: In
        values:
          - api
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: 
          - t
          - c
          - r
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values: 
          - medium
          - large
          - xlarge
          - 2xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values: 
          - on-demand

  - name: gpu-nodepool
    taints:
      - key: nvidia.com/gpu
        value: "true"
        effect: NoSchedule
      - key: workload-type
        value: gpu
        effect: NoSchedule
    labels:
      workload-type: gpu
      nvidia.com/gpu: "true"
    requirements:
      - key: workload-type
        operator: In
        values:
          - gpu
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values: 
          - g4dn
          - g4ad
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values: 
          - xlarge
          - 2xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values: 
          - spot
      - key: "topology.kubernetes.io/zone"
        operator: In
        values:
          - eu-central-1a
          - eu-central-1b
          - eu-central-1c
      - key: "kubernetes.io/arch"
        operator: In
        values:
          - amd64
      - key: "kubernetes.io/os"
        operator: In
        values:
          - linux

  - name: edge-nodepool
    taints:
      - key: workload-type
        value: edge
        effect: NoSchedule
    labels:
      workload-type: edge
    requirements:
      - key: workload-type
        operator: In
        values:
          - edge
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
          - m
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
          - m5zn
          - m6i
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
          - xlarge
          - 2xlarge
          - 3xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values:
          - on-demand