domainFilters:
  - prod.euc1.example.com

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/prod-euc1-python-ai-eks-private-eks-external-dns

env:
  - name: AWS_DEFAULT_REGION
    value: eu-central-1
txtOwnerId: prod-euc1-python-ai-eks-private

