installCRDs: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

log:
  level: warn

webhook:
  log:
    level: warn

certController:
  log:
    level: warn