settings:
  clusterName: "prod-use1-web-eks"
  clusterEndpoint: "https://432267D0DB8D0D41577E51194894C9ED.gr7.us-east-1.eks.amazonaws.com"
  interruptionQueue: "Karpenter-prod-use1-web-eks"
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/KarpenterController-20250918121239098900000001"
