{{- if .Values.clusterSecretStore.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.clusterSecretStore.serviceAccount.name }}
  namespace: {{ .Values.clusterSecretStore.serviceAccount.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.clusterSecretStore.serviceAccount.roleArn }}
{{- end }}
