name: web
clusterPrefixName: web-eks
deployment:
  enabled: true
  image:
    tag: 'demo_ecaaa4d'
  replicas: 1
  deploymentStrategy: RollingUpdate
  maxSurge: 25%
  maxUnavailable: 25%
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    admission.datadoghq.com/enabled: "false"
    tags.datadoghq.com/service: web
    tags.datadoghq.com/project: web
    tags.datadoghq.com/team: software
    tags.datadoghq.com/env: demo
  podAnnotations:
    ad.datadoghq.com/web.logs: '[{"source":"elixir", "service":"web", "tags":["env:demo","project:web","team:software"]}]'
# autoscaling:
#   minReplicas: 1
#   maxReplicas: 2

serviceAccount:
  create: true

service:
  enabled: true
  targetPort: 4000

additionalEnvsFrom:
  - name: HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

additionalEnvs:
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://$(HOST_IP):4318"

config:
  data:
    PHX_HOST: "web.demo.euc1.example.com"
    S3_BUCKET: "demo-euc1-example-projects"
    S3_REGION: "eu-central-1"
    AWS_MAILER_ENDPOINT: https://email.eu-central-1.amazonaws.com
    AWS_MAILER_FROM: "user@example.com"
    NOTIFICATION_ADDRESS: "user@example.com"
    PYTHON_AI_NODE_ENDPOINT_URL: "https://python-ai-non-gpu.demo.euc1.example.com"
    DEFAULT_PROGRAMMER_ID: "8"
    DEFAULT_FEEDBACK_USER_EMAIL: "user@example.com"
    CAM_ANALYTICS_ENABLED: "true"
    CAM_ANALYTICS_EMAILS: "user@example.com"
    CAM_ANALYTICS_REPORTING_INTERVAL: "3600000"
    AIRTABLE_BASE: "example-airtable-base"
    LMS_HUB_LOG_LEVEL: "debug"
    SQS_QUEUE_URL: https://sqs.eu-central-1.amazonaws.com/123456789012/example-queue
secrets:
  template:
    SECRET_KEY_BASE: "{{ .keyBase }}"
    DATABASE_URL: "ecto://{{ .username }}:{{ .password | urlquery }}@{{ .rdsWriterEndpoint }}/datacore"
    S3_ACCESS_KEY_ID: "{{ .s3_access_key }}"
    S3_SECRET_ACCESS_KEY: "{{ .s3_secret }}"
    AIRTABLE_API_KEY: "{{ .airtable_key }}"
    LLM_API_KEY: "{{ .open_ai_key }}"
  data:
    - secretKey: open_ai_key
      remoteRef:
        key: "Application/example/default-secret"
        property: "OPEN_AI_KEY"  
    - secretKey: airtable_key
      remoteRef:
        key: "Application/example/default-secret" 
        property: "AIRTABLE_KEY"
    - secretKey: keyBase
      remoteRef:
        key: "Application/example/default-secret"
        property: "SECRET_KEY_BASE"
    - secretKey: rdsWriterEndpoint
      remoteRef:
        key: "Application/example/default-secret" 
        property: "RDS_WRITER_ENDPOINT"
    - secretKey: password
      remoteRef:
        key: "rds!cluster-example" 
        property: "password"
    - secretKey: username
      remoteRef:
        key: "rds!cluster-example" 
        property: "username"
    - secretKey: s3_access_key
      remoteRef:
        key: "Application/example/default-secret" 
        property: "S3_ACCESS_KEY"
    - secretKey: s3_secret
      remoteRef:
        key: "Application/example/default-secret" 
        property: "S3_SECRET"
ingress:
  enabled: true
  groupName: demo-euc1-web-eks-public
  internet: true
  annotations:
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-Res-2021-06
    alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:eu-central-1:123456789012:regional/webacl/demo-euc1-waf-acl-regional/00000000-0000-0000-0000-000000000000"
    
# pdb:
#   enabled: false
#   minAvailable: 1

resources:
  limits:
    memory: 64Gi
    cpu: "8"
  requests:
    memory: 56Gi  
    cpu: "6"
