global:
  environment: dev
  short_environment: dev
  region: us-gov-west-1
  short_region: usgw1
  repo: "123456789012.dkr.ecr.us-gov-west-1.amazonaws.com"
  certificate: "arn:aws-us-gov:acm:us-gov-west-1:123456789012:certificate/00000000-0000-0000-0000-000000000000"
  example_private_hostname: dev.usgw1.example.com
  example_public_hostname: example.com
  account: "123456789012"

name: "web"

deployment:
  enabled: true
  image:
    tag: "1.0.0"
  replicas: 1
  deploymentStrategy: RollingUpdate
  maxSurge: 25%
  maxUnavailable: 25%

serviceAccount:
  create: true

service:
  enabled: true

config:
  bobo: "true"

secrets:
  data:
    - secretKey: "credentials"
      remoteRef:
        key: "Application/example/default-secret"
        property: "credentials"

ingress:
  enabled: true
  internet: true

pdb:
  enabled: true
  minAvailable: 1