{{- if .Values.config }}
apiVersion: v1  
kind: ConfigMap
metadata:
  name: '{{ .Values.name }}-configmap'
  {{- if .Values.config.annotations }}
  annotations:
    {{- range $key, $value := .Values.config.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
data:
  {{- $environment := .Values.global.environment }}
  {{- toYaml .Values.config.data | nindent 2 }}
{{- end }}
