{{- if .Values.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }} 
  {{- if .Values.secrets.annotations }}
  annotations:
    {{- range $key, $value := .Values.secrets.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  refreshInterval: 10h
  secretStoreRef:
    name: {{ .Values.secrets.storeName | default "applications-secretstore" }}
    kind: {{ .Values.secrets.storeKind | default "SecretStore" }}
  target:
    name: {{ .Values.name }}-secret
    creationPolicy: Owner
    {{- if .Values.secrets.template }}
    template:
      engineVersion: v2
      data:
        {{- toYaml .Values.secrets.template | nindent 8 }}
    {{- end }}
  data:
{{- range $item := .Values.secrets.data }}
  - secretKey: "{{ $item.secretKey }}"
    remoteRef:
      key: "{{ $item.remoteRef.key }}"
      property: "{{ $item.remoteRef.property }}"
{{- end }}
{{- end }}
